# Maintainer: FrancoStino <info@davideladisa.it>
pkgname=antigravity-manager-bin
pkgver=0.10.0
pkgrel=2
pkgdesc="Professional multi-account manager for Google Gemini & Claude AI"
arch=('x86_64' 'aarch64')
url="https://github.com/Draculabo/AntigravityManager"
license=('LicenseRef-CC-BY-NC-SA-4.0')
depends=('gtk3' 'nss' 'alsa-lib')
optdepends=(
    'libappindicator-gtk3: system tray support'
    'libnotify: desktop notifications'
)
provides=('antigravity-manager')
conflicts=('antigravity-manager' 'antigravity-manager-git')

# Arch-specific upstream RPM sources
# Upstream changed filename convention from v0.4.0+ : antigravity-manager-* → Antigravity.Manager-*
_upstream_base="https://github.com/Draculabo/AntigravityManager/releases/download/v${pkgver}"
source_x86_64=("Antigravity.Manager-${pkgver}-1.x86_64.rpm::${_upstream_base}/Antigravity.Manager-${pkgver}-1.x86_64.rpm")
source_aarch64=("Antigravity.Manager-${pkgver}-1.aarch64.rpm::${_upstream_base}/Antigravity.Manager-${pkgver}-1.aarch64.rpm")
sha256sums_x86_64=('a2f630f4a812bb1d68f8429f0e7d5393a6f567866a2c69ebe6122d4c1bc11bab')
sha256sums_aarch64=('61a80cdcec689974bcd77a8fd75af8111dc2b843bc2c9574f90de044a268b28c')
noextract=("Antigravity.Manager-${pkgver}-1.x86_64.rpm"
           "Antigravity.Manager-${pkgver}-1.aarch64.rpm")

package() {
    cd "${srcdir}"

    # Select the correct RPM for the current architecture
    case "$CARCH" in
        x86_64)  _rpm="Antigravity.Manager-${pkgver}-1.x86_64.rpm" ;;
        aarch64) _rpm="Antigravity.Manager-${pkgver}-1.aarch64.rpm" ;;
        *) echo "ERROR: Unsupported architecture: $CARCH"; exit 1 ;;
    esac

    # Extract RPM directly into pkgdir
    bsdtar -xf "${_rpm}" -C "${pkgdir}"

    # Remove /usr/lib/.build-id — these ELF debuginfo symlinks are generated by
    # the RPM toolchain and are not needed on Arch Linux. Because build-IDs are
    # derived from binary content, Electron apps sharing the same Electron/
    # Chromium version produce identical IDs, causing conflicts with other
    # Electron-based packages (e.g. discord, bitwarden-bin, flywheel, etc.).
    rm -rf "${pkgdir}/usr/lib/.build-id"

    # Find where the binary actually is (handles both /usr/bin and /opt/** layouts)
    BINARY=$(find "${pkgdir}" -name "antigravity-manager" -type f 2>/dev/null | head -1)

    if [ -n "$BINARY" ]; then
        chmod 755 "$BINARY"

        # Ensure /usr/bin symlink exists
        install -dm755 "${pkgdir}/usr/bin"
        ln -sf "${BINARY#${pkgdir}}" "${pkgdir}/usr/bin/antigravity-manager"

        # Install license if present
        LICENSE=$(find "${pkgdir}" -name "LICENSE*" -type f 2>/dev/null | head -1)
        if [ -n "$LICENSE" ]; then
            install -Dm644 "$LICENSE" \
                "${pkgdir}/usr/share/licenses/${pkgname}/LICENSE"
        fi
    else
        echo "ERROR: Could not find antigravity-manager binary"
        exit 1
    fi
}
